In [1]:
import numpy as np

# Pregunta 1

In [2]:
A = np.array([[0, 1, -2], [2, 3, -1], [1, -1, 5]])
B = np.array([[1, -1, 2, 1], [2, -2, 2, -2], [-1, 2, 1, 2]])
C = np.array([[2], [0], [1], [-4]])

In [3]:
A.dot(B)

array([[  4,  -6,   0,  -6],
       [  9, -10,   9,  -6],
       [ -6,  11,   5,  13]])

In [4]:
B.dot(C)

array([[ 0],
       [14],
       [-9]])

In [5]:
B.transpose()

array([[ 1,  2, -1],
       [-1, -2,  2],
       [ 2,  2,  1],
       [ 1, -2,  2]])

In [6]:
B.transpose().dot(A)

array([[ 3,  8, -9],
       [-2, -9, 14],
       [ 5,  7, -1],
       [-2, -7, 10]])

In [7]:
C.transpose().dot(B.transpose())

array([[ 0, 14, -9]])

# Pregunta 2

In [8]:
A = np.array([[0, 1], [0, 1]])
B = np.array([[-1, -1], [0, 0]])

In [19]:
np.linalg.matrix_power(A+B, 2)

array([[1, 0],
       [0, 1]])

In [20]:
np.linalg.matrix_power(A, 2) + 2*A.dot(B) + np.linalg.matrix_power(B, 2)

array([[1, 2],
       [0, 1]])

In [15]:
C = A+B
np.linalg.matrix_power(C, 3)

array([[-1,  0],
       [ 0,  1]])

In [25]:
np.linalg.matrix_power(A, 3) + 3 * np.linalg.matrix_power(A, 2).dot(B) + 2*A.dot(B) + 3 * A.dot(np.linalg.matrix_power(B, 2)) + np.linalg.matrix_power(B, 3) 

array([[-1,  0],
       [ 0,  1]])

# Pregunta 3

In [27]:
A = np.array([[-1, 1, -2], [1, 1, 0], [2, 1, 1]])
B = np.array([[-1, 2, 3, 4, 5], [1, 2, 1, 3, 2], [0, 4, 4, 7, 7]])

In [28]:
np.linalg.matrix_rank(A)

2

In [29]:
np.linalg.matrix_rank(B)

2

# Pregunta 4

In [31]:
A = np.array([[1, 2, 0], [0, 1, -1], [0, 0, 2]])
B = np.array([[1j, 0, 0], [0, 0, 1], [1, 1j, 0]])

In [32]:
np.linalg.inv(A)

array([[ 1. , -2. , -1. ],
       [ 0. ,  1. ,  0.5],
       [ 0. ,  0. ,  0.5]])

In [33]:
np.linalg.inv(B)

array([[0.-1.j, 0.+0.j, 0.+0.j],
       [1.+0.j, 0.+0.j, 0.-1.j],
       [0.+0.j, 1.+0.j, 0.+0.j]])